name: stackture_mobile
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  intl: ^0.19.0

  url_launcher: ^6.1.11
  reorderable_grid_view: ^2.2.8
  flutter_fancy_tree_view: ^1.6.0
  http: ^1.3.0
  web_socket_channel: ^3.0.2
  animated_text_kit: ^4.2.2
  flutter_launcher_icons: ^0.14.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:

  fonts:
  - family: LilitaOne
    fonts:
      - asset: assets/fonts/LilitaOne-Regular.ttf
  - family: VarelaRound
    fonts:
      - asset: assets/fonts/VarelaRound-Regular.ttf


  uses-material-design: true
  assets:
    - assets/images/books.png
    - assets/images/chatbot.png
    - assets/images/signout.png
    - assets/images/left.png


#flutter_icons:
#  android: true
#  ios: true
#  image_path: "assets/icons/app_icon.png"
#  adaptive_icon_foreground: "assets/icons/foreground.png"
#  adaptive_icon_background: "assets/icons/background.png"
